		// Define the arrays of names
		const greenFlags = ["Good communication skills",
"Mutual respect for each other's opinions and beliefs",
"Shared values and goals",
"Trustworthiness and honesty",
"Ability to compromise and find common ground",
"Supportiveness and encouragement towards each other's personal growth and development",
"Mutual appreciation and gratitude for each other",
"Emotional intelligence and self-awareness",
"Willingness to apologize and make amends when necessary",
"Shared sense of humor and ability to have fun together",
"Shared interests and hobbies",
"Willingness to try new things together",
"Mutual respect for each other's privacy and personal space",
"Healthy boundaries and respect for each other's boundaries",
"Ability to handle conflicts and disagreements in a respectful and constructive manner",
"Openness to discussing and resolving issues together",
"Ability to listen to and validate each other's feelings and emotions",
"Willingness to show affection and express love in a healthy way",
"Consistent effort in maintaining emotional connection and intimacy",
"Willingness to seek outside help or support when needed",
"Respectful behavior towards people in service roles",
"Respectful behavior towards animals or pets",
"Willingness to make compromises on important decisions",
"Consistent effort in maintaining a healthy and active sex life",
"Willingness to prioritize the relationship over personal desires or interests",
"Respectful behavior towards partner's cultural background or traditions",
"Willingness to communicate openly about important topics or issues",
"Consistent effort in maintaining physical intimacy",
"Respectful behavior towards partner's religious beliefs or practices",
"Ability to handle jealousy or insecurity in a healthy way",
"Willingness to seek counseling or therapy when needed",
"Respect for partner's values or beliefs",
"Consistent effort in maintaining shared responsibilities or household chores",
"Ability to handle emotional distress or trauma in a healthy way",
"Respectful behavior towards partner's family or friends",
"Willingness to compromise on important lifestyle choices (e.g., having children, where to live)",
"Willingness to make time for the relationship and prioritize quality time together",
"Consistent effort in showing affection and expressing love in a healthy way",
"Ability to handle conflict or disagreements in a respectful and constructive manner",
"Interest and support towards partner's creative or artistic pursuits",
"Willingness to take responsibility for personal growth and development",
"Respectful behavior towards partner's mental health",
"Ability to make compromises on important relationship issues",
"Consistent effort in maintaining emotional connection",
"Ability to be vulnerable and express emotions in a healthy way",
"Respect for partner's sexual boundaries or desires",
"Interest and support towards partner's social life or friendships",
"Respect for partner's privacy and personal space",
"Interest and support towards partner's family or family events","Willingness to try new things and explore new experiences together",
"Respectful behavior towards partner's dietary restrictions or preferences",
"Ability to apologize and take responsibility for mistakes",
"Willingness to compromise on household decor or style",
"Consistent effort in showing appreciation and gratitude towards each other",
"Ability to plan and make decisions together as a team",
"Interest and support towards partner's career or professional aspirations",
"Respect for partner's financial goals or priorities",
"Willingness to give and receive constructive feedback in a respectful way",
"Ability to support each other through difficult times or challenges",
"Interest and support towards partner's hobbies or interests",
"Willingness to engage in shared activities or rituals (e.g., cooking, exercise)",
"Respectful behavior towards partner's gender identity or expression",
"Ability to celebrate each other's successes and accomplishments",
"Willingness to discuss and plan for future goals or milestones together",
"Consistent effort in maintaining healthy communication and dialogue",
"Interest and support towards partner's spiritual beliefs or practices",
"Respect for partner's personal boundaries and autonomy",
"Willingness to make sacrifices for each other's happiness or well-being",
"Ability to communicate love and affection in different ways (e.g., through physical touch, acts of service)",
"Interest and support towards partner's education or personal growth",
"Willingness to learn and grow together as a couple",
"Consistent effort in maintaining trust and honesty",
"Ability to express vulnerability and trust each other with sensitive information",
"Willingness to support each other's social or political causes",
"Interest and support towards partner's travel or adventure goals",
"Respectful behavior towards partner's disability or chronic illness",
"Ability to adapt to changing circumstances or situations together",
"Willingness to seek compromise and find common ground in disagreements",
"Consistent effort in maintaining a healthy work-life balance",
"Interest and support towards partner's mental or physical health goals",
"Respect for partner's boundaries around personal time or alone time",
"Willingness to work through conflicts or disagreements to find resolution",
"Ability to express empathy and understanding towards each other's perspectives",
"Willingness to learn from each other and grow as individuals and as a couple",
"Interest and support towards partner's philanthropic or volunteer work",
"Respect for partner's decision-making process and ability to make choices autonomously",
"Willingness to take responsibility for each other's emotional well-being and happiness",
"Ability to celebrate each other's differences and unique qualities",
"Willingness to acknowledge and work through any underlying issues or conflicts in the relationship",
"Consistent effort in maintaining a healthy balance of give and take in the relationship",
"Interest and support towards partner's personal hobbies or passions",
"Respectful behavior towards partner's past experiences or trauma",
"Ability to express gratitude and appreciation for each other's contributions to the relationship",
"Willingness to create and maintain shared goals and aspirations for the relationship",
"Interest and support towards partner's parenting goals or values",
"Respect for partner's cultural or ethnic identity",
"Willingness to invest time and effort into the relationship for the long-term",
"Ability to express affection and love through nonverbal communication (e.g., through physical touch, eye contact)",
"Willingness to continuously work on and improve the relationship over time",
];

const redFlags = ["Lack of communication or dishonesty",
"Disrespectful behavior or language",
"Controlling behavior or jealousy",
"Isolation from family or friends",
"Manipulative behavior or emotional blackmail",
"Cheating or infidelity",
"Lack of trust or honesty",
"Blaming the partner for personal problems",
"Refusal to take responsibility for mistakes",
"Excessive anger or violence",
"Lack of empathy or consideration for partner's feelings",
"Financial dishonesty or irresponsibility",
"Substance abuse or addiction issues",
"Refusal to compromise or work through conflicts",
"Lack of support for partner's goals or aspirations",
"Lack of respect for partner's boundaries or privacy",
"Refusal to take responsibility for personal growth",
"Lack of accountability for actions or behavior",
"Refusal to seek help or support for personal problems",
"Inability to apologize or make amends",
"Gaslighting or other forms of emotional abuse",
"Disrespectful behavior towards partner's family or friends",
"Refusal to respect partner's beliefs or values",
"Disregard for partner's physical or emotional safety",
"Refusal to seek help for mental health issues",
"Refusal to participate in important events or milestones in the relationship",
"Lack of interest in spending quality time together",
"Disinterest in partner's hobbies or interests",
"Inability to compromise or find common ground",
"Lack of support during difficult times",
"Unwillingness to listen to partner's perspective",
"Disinterest in partner's feelings or emotions",
"Emotional withdrawal or shutting down",
"Lack of affection or physical intimacy",
"Disrespectful behavior towards people in service roles",
"Disrespectful behavior towards animals or pets",
"Refusal to take responsibility for household chores or responsibilities",
"Lack of motivation or ambition",
"Refusal to work towards shared goals or aspirations",
"Inability to follow through on commitments",
"Inability to communicate effectively during conflict",
"Disregard for partner's sexual boundaries or desires",
"Lack of effort in maintaining the relationship",
"Avoidance of discussing important topics or issues",
"Disinterest in partner's career or professional life",
"Lack of emotional support during major life events",
"Inability to handle stress or pressure in a healthy way",
"Disinterest in partner's health or well-being",
"Lack of gratitude or appreciation for partner's efforts",
"Disrespectful behavior towards partner's culture or background",
"Disinterest in partner's spiritual practices or beliefs",
"Refusal to participate in important religious or cultural events",
"Refusal to compromise on major decisions",
"Disregard for partner's opinion or input",
"Inability to take criticism or feedback constructively",
"Lack of emotional intelligence or self-awareness",
"Inability to apologize or admit fault",
"Refusal to seek outside help or support when needed",
"Inability to prioritize the relationship over other commitments",
"Disinterest in partner's education or intellectual pursuits",
"Lack of boundaries or respect for partner's boundaries",
"Disregard for partner's physical health or safety",
"Lack of responsibility in handling finances or debts",
"Disinterest in maintaining a healthy and active sex life",
"Lack of interest in maintaining emotional intimacy","Disrespectful behavior towards partner's gender or sexuality",
"Refusal to compromise on important lifestyle choices (e.g., having children, where to live)",
"Refusal to make time for the relationship or prioritize quality time together",
"Inability to show affection or express love in a healthy way",
"Inability to handle conflict or disagreements in a respectful manner",
"Disinterest in partner's creative or artistic pursuits",
"Refusal to take responsibility for personal growth and development",
"Disrespectful behavior towards partner's mental health",
"Inability to make compromises on important decisions",
"Lack of effort in maintaining emotional connection",
"Inability to be vulnerable or express emotions in a healthy way",
"Refusal to respect partner's sexual boundaries or desires",
"Disinterest in partner's social life or friendships",
"Disregard for partner's privacy or personal space",
"Disinterest in partner's family or family events",
"Refusal to seek help or support for personal issues",
"Inability to handle changes or transitions in a healthy way",
"Disrespectful behavior towards partner's physical appearance or body",
"Inability to make time for self-care and personal well-being",
"Disinterest in partner's personal interests or hobbies",
"Refusal to make compromises on important relationship issues",
"Disregard for partner's feelings or emotions during conflict",
"Inability to handle criticism or feedback constructively",
"Disinterest in partner's cultural background or traditions",
"Refusal to communicate about important topics or issues",
"Lack of effort in maintaining physical intimacy",
"Disrespectful behavior towards partner's religious beliefs or practices",
"Inability to prioritize the relationship over personal desires or interests",
"Disinterest in partner's career or professional aspirations",
"Inability to handle jealousy or insecurity in a healthy way",
"Refusal to seek counseling or therapy when needed",
"Disregard for partner's values or beliefs",
"Lack of effort in maintaining shared responsibilities or household chores",
"Inability to handle emotional distress or trauma in a healthy way",
"Disrespectful behavior towards partner's family or friends"];


		// Initialize an empty array to keep track of the displayed names
		let displayedNames = [];

// Function to display a random name from the respective array
function displayRandomName(flag) {
  let namesArray;
  if (flag === 'green') {
    namesArray = greenFlags;
  } else if (flag === 'red') {
    namesArray = redFlags;
  }

  if (displayedNames.length === namesArray.length) {
    // Reset the displayedNames array if all names have been displayed
    displayedNames = [];
  }

  let randomIndex = Math.floor(Math.random() * namesArray.length);
  let randomName = namesArray[randomIndex];

  while (displayedNames.includes(randomName)) {
    // Generate a new random name if the name has already been displayed
    randomIndex = Math.floor(Math.random() * namesArray.length);
    randomName = namesArray[randomIndex];
  }

  // Add the name to the displayedNames array and display it in the text display area
  displayedNames.push(randomName);
  let textDisplay = document.querySelector('.text-display');
  textDisplay.innerHTML = randomName;
}
